sudo: required
services:
  - docker

before_install:
  - docker build -t skaldat/docker-kubernetes-course-app -f Dockerfile.dev .

script:
  - docker run -e CI=true skaldat/docker-kubernetes-course-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "DockerKubernetesCourseApp"
  env: "Dockerkubernetescourseapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-104288539544"
  bucket_path: "DockerKubernetesCourseApp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"